export { default as LayoutPage } from './LayoutPage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as ErrorPage } from './ErrorPage';
export { default as ForgetPasswordPage } from './ForgetPasswordPage';
export { default as DashboardPage } from './DashboardPage';
export { default as HomePage } from './HomePage';
export { default as AboutPage } from './AboutPage';
export { default as ContactPage } from './ContactPage';
